/* Generated By:JavaCC: Do not edit this line. SPARQLParserConstants.java */
/*
 * (c) Copyright 2004, 2005, 2006, 2007, 2008 Hewlett-Packard Development Company, LP
 * All rights reserved.
 */

package com.hp.hpl.jena.sparql.lang.sparql ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPARQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS = 6;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int IRIref = 8;
  /** RegularExpression Id. */
  int PNAME_NS = 9;
  /** RegularExpression Id. */
  int PNAME_LN = 10;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 11;
  /** RegularExpression Id. */
  int VAR1 = 12;
  /** RegularExpression Id. */
  int VAR2 = 13;
  /** RegularExpression Id. */
  int LANGTAG = 14;
  /** RegularExpression Id. */
  int A2Z = 15;
  /** RegularExpression Id. */
  int A2ZN = 16;
  /** RegularExpression Id. */
  int KW_A = 17;
  /** RegularExpression Id. */
  int BASE = 18;
  /** RegularExpression Id. */
  int PREFIX = 19;
  /** RegularExpression Id. */
  int SELECT = 20;
  /** RegularExpression Id. */
  int DISTINCT = 21;
  /** RegularExpression Id. */
  int REDUCED = 22;
  /** RegularExpression Id. */
  int DESCRIBE = 23;
  /** RegularExpression Id. */
  int CONSTRUCT = 24;
  /** RegularExpression Id. */
  int ASK = 25;
  /** RegularExpression Id. */
  int LIMIT = 26;
  /** RegularExpression Id. */
  int OFFSET = 27;
  /** RegularExpression Id. */
  int ORDER = 28;
  /** RegularExpression Id. */
  int BY = 29;
  /** RegularExpression Id. */
  int ASC = 30;
  /** RegularExpression Id. */
  int DESC = 31;
  /** RegularExpression Id. */
  int NAMED = 32;
  /** RegularExpression Id. */
  int FROM = 33;
  /** RegularExpression Id. */
  int WHERE = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int GRAPH = 36;
  /** RegularExpression Id. */
  int OPTIONAL = 37;
  /** RegularExpression Id. */
  int UNION = 38;
  /** RegularExpression Id. */
  int FILTER = 39;
  /** RegularExpression Id. */
  int BOUND = 40;
  /** RegularExpression Id. */
  int STR = 41;
  /** RegularExpression Id. */
  int DTYPE = 42;
  /** RegularExpression Id. */
  int LANG = 43;
  /** RegularExpression Id. */
  int LANGMATCHES = 44;
  /** RegularExpression Id. */
  int IS_URI = 45;
  /** RegularExpression Id. */
  int IS_IRI = 46;
  /** RegularExpression Id. */
  int IS_BLANK = 47;
  /** RegularExpression Id. */
  int IS_LITERAL = 48;
  /** RegularExpression Id. */
  int REGEX = 49;
  /** RegularExpression Id. */
  int SAME_TERM = 50;
  /** RegularExpression Id. */
  int TRUE = 51;
  /** RegularExpression Id. */
  int FALSE = 52;
  /** RegularExpression Id. */
  int FEEDBACK = 53;
  /** RegularExpression Id. */
  int APPLYREQUEST = 54;
  /** RegularExpression Id. */
  int LOOP = 55;
  /** RegularExpression Id. */
  int FOR = 56;
  /** RegularExpression Id. */
  int END = 57;
  /** RegularExpression Id. */
  int SYNTACTIC = 58;
  /** RegularExpression Id. */
  int SEMANTIC = 59;
  /** RegularExpression Id. */
  int ENTAILSCHANGED = 60;
  /** RegularExpression Id. */
  int CHANGEHANDLER = 61;
  /** RegularExpression Id. */
  int UNIQUE = 62;
  /** RegularExpression Id. */
  int IF = 63;
  /** RegularExpression Id. */
  int THEN = 64;
  /** RegularExpression Id. */
  int VAR = 65;
  /** RegularExpression Id. */
  int DIGITS = 66;
  /** RegularExpression Id. */
  int INTEGER = 67;
  /** RegularExpression Id. */
  int DECIMAL = 68;
  /** RegularExpression Id. */
  int DOUBLE = 69;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 70;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 71;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 72;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 73;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 74;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 75;
  /** RegularExpression Id. */
  int EXPONENT = 76;
  /** RegularExpression Id. */
  int QUOTE_3D = 77;
  /** RegularExpression Id. */
  int QUOTE_3S = 78;
  /** RegularExpression Id. */
  int ECHAR = 79;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 80;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 81;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 82;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 83;
  /** RegularExpression Id. */
  int LPAREN = 84;
  /** RegularExpression Id. */
  int RPAREN = 85;
  /** RegularExpression Id. */
  int NIL = 86;
  /** RegularExpression Id. */
  int LBRACE = 87;
  /** RegularExpression Id. */
  int RBRACE = 88;
  /** RegularExpression Id. */
  int LBRACKET = 89;
  /** RegularExpression Id. */
  int RBRACKET = 90;
  /** RegularExpression Id. */
  int ANON = 91;
  /** RegularExpression Id. */
  int SEMICOLON = 92;
  /** RegularExpression Id. */
  int COMMA = 93;
  /** RegularExpression Id. */
  int DOT = 94;
  /** RegularExpression Id. */
  int EQ = 95;
  /** RegularExpression Id. */
  int NE = 96;
  /** RegularExpression Id. */
  int GT = 97;
  /** RegularExpression Id. */
  int LT = 98;
  /** RegularExpression Id. */
  int LE = 99;
  /** RegularExpression Id. */
  int GE = 100;
  /** RegularExpression Id. */
  int BANG = 101;
  /** RegularExpression Id. */
  int TILDE = 102;
  /** RegularExpression Id. */
  int COLON = 103;
  /** RegularExpression Id. */
  int SC_OR = 104;
  /** RegularExpression Id. */
  int SC_AND = 105;
  /** RegularExpression Id. */
  int PLUS = 106;
  /** RegularExpression Id. */
  int MINUS = 107;
  /** RegularExpression Id. */
  int STAR = 108;
  /** RegularExpression Id. */
  int SLASH = 109;
  /** RegularExpression Id. */
  int DATATYPE = 110;
  /** RegularExpression Id. */
  int AT = 111;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 112;
  /** RegularExpression Id. */
  int PN_CHARS_U = 113;
  /** RegularExpression Id. */
  int PN_CHARS = 114;
  /** RegularExpression Id. */
  int PN_PREFIX = 115;
  /** RegularExpression Id. */
  int PN_LOCAL = 116;
  /** RegularExpression Id. */
  int VARNAME = 117;
  /** RegularExpression Id. */
  int UNKNOWN = 118;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"filter\"",
    "\"bound\"",
    "\"str\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"true\"",
    "\"false\"",
    "\"feedback\"",
    "\"applyrequest\"",
    "\"loop\"",
    "\"for\"",
    "\"end\"",
    "\"syntactic\"",
    "\"semantic\"",
    "\"entailschanged\"",
    "\"changehandler\"",
    "\"unique\"",
    "\"if\"",
    "\"then\"",
    "<VAR>",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
